<?php

namespace Basster\MovieDbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository {

    public function countAll() {
        return $this->getEntityManager()->createQuery('SELECT COUNT(m) FROM BassterMovieDbBundle:Movie m')->getSingleScalarResult();
    }
    
    public function findByNamePart($part) {
        
        $dql = "SELECT m.title as value
            FROM BassterMovieDbBundle:Movie m 
            WHERE m.title LIKE '%" . $part . "%'
            ORDER BY m.title ASC";
        
        return $this->getEntityManager()->createQuery($dql)->getResult();
    }
}